godwokenrises/godwoken-web3

packages/api-server/app.js, packages/api-server/src/methods/modules/eth.ts, packages/api-server/src/methods/types.ts, packages/api-server/src/methods/validator.ts
**Test case:**
```sh
curl -v http://127.0.0.1:8024 -X POST -H "Content-Type: application/json" -d '{
"jsonrpc":"2.0",
"method":"eth_sendRawTransaction",
"params":["0xf901e980017b8080b9019e608060405234801561001057600080fd5b5061017e806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c80632e64cec11461003b5780636057361d14610059575b600080fd5b610043610075565b604051610050919061010c565b60405180910390f35b610073600480360381019061006e91906100d4565b61007e565b005b60008054905090565b806000819055507f93fe6d397c74fdf1402a8b72e47b68512f0510d7b98a4bc4cbdf6ac7108b3c59816040516100b4919061010c565b60405180910390a150565b6000813590506100ce81610131565b92915050565b6000602082840312156100e657600080fd5b60006100f4848285016100bf565b91505092915050565b61010681610127565b82525050565b6000602082 …
```
=> fix error handling in sendRawTransaction method

packages/api-server/src/methods/modules/gw.ts
```json
{
"id": 2,
"error": {
"code": -32098,
"message": "JSONRPCError: server error {\"code\":-32602,\"message\":\"Invalid params\"}"
}
}
```
To
```json
{
"error": {
"code": -32602,
"message": "Invalid params"
},
"id": 1
}
```
=> refactor: Update gw_ error resolve

README.md, packages/api-server/src/methods/modules/eth.ts
request:
```json
{
"id": 2,
"method": "eth_call",
"params": [
{
"to": "0xef2f7e0ad8b8171a952115448602de4b66129496",
"data": "0x6d4ce63c"
},
"latest"
]
}
```
Origin response:
```json
{
"id": 2,
"error": {
"message": "JSONRPCError: server error {\"code\":0,\"message\":\"invalid exit code -1\"}"
}
}
```
Now:
```json
{
"id": 2,
"result": "0x000000000000000000000000000000000000000000000000000000000000029a"
}
```
=> feat: Add default from config

packages/api-server/src/methods/modules/eth.ts, packages/godwoken/src/client.ts, packages/godwoken/src/types.ts
Get the current price per gas in shannon from Godwoken RPC:
- https://github.com/nervosnetwork/godwoken/pull/415
=> feat: implement eth_gasPrice RPC

packages/api-server/src/methods/modules/eth.ts, packages/godwoken/src/client.ts, packages/godwoken/src/types.ts
Reverts nervosnetwork/godwoken-web3#83
=> Revert "feat: implement eth_gasPrice RPC"

packages/api-server/src/cache/constant.ts, packages/api-server/src/methods/modules/gw.ts
```
web3_1          | [1] POST / 200 8.499 ms - 39
web3_1          | [1] request.method: gw_get_account_id_by_script_hash
web3_1          | [1] using cache: 0xdfb94d6794165b96668b4308607afc05790dc2110867d3370ceb8a412902e7b4 -> 0x2
web3_1          | [1] POST / 200 0.417 ms - 39
web3_1          | [1] request.method: gw_get_account_id_by_script_hash
web3_1          | [1] using cache: 0xdfb94d6794165b96668b4308607afc05790dc2110867d3370ceb8a412902e7b4 -> 0x2
web3_1          | [1] POST / 200 0.423 ms - 39
web3_1          | [1] request.method: gw_get_account_id_by_script_hash
web3_1          | [1] using cache: 0xdfb94d6794165b96668b4308607afc05790dc2110867d3370ceb8a412902e7b4 -> 0x2
web3_1          | [1] POST / 200 0.370 ms - 39
web3_1          | [1] request.method: …
```
=> Cache get account id by script hash

README.md, packages/api-server/src/base/env-config.ts, packages/api-server/src/cache/constant.ts, packages/api-server/src/cache/data.ts, packages/api-server/src/methods/modules/gw.ts, packages/api-server/src/methods/modules/poly.ts, packages/api-server/src/util.ts, packages/godwoken/src/client.ts
redis key will be like:
```sh
Poly:executeRawL2Transaction:key:0xba03fe2c1bc8716840c4c5200b337f285448c3db81d953de
Poly:executeRawL2Transaction:lock:0xba03fe2c1bc8716840c4c5200b337f285448c3db81d953de
Poly:executeRawL2Transaction:channel:0xba03fe2c1bc8716840c4c5200b337f285448c3db81d953de
```
=> feat: add cache for executeRawL2Tx

packages/api-server/src/methods/modules/gw.ts
- https://github.com/nervosnetwork/godwoken-web3/pull/168
=> fix(compatibility): use full node for gw_get_last_submitted_info

packages/api-server/src/methods/modules/gw.ts
- https://github.com/nervosnetwork/godwoken-web3/pull/168
=> fix(v0.12.x): use full node for gw_get_last_submitted_info

README.md, packages/api-server/src/base/env-config.ts, packages/api-server/src/cache/constant.ts, packages/api-server/src/cache/data.ts, packages/api-server/src/methods/modules/gw.ts, packages/api-server/src/methods/modules/poly.ts, packages/api-server/src/util.ts, packages/godwoken/src/client.ts
- https://github.com/nervosnetwork/godwoken-web3/pull/156
=> feat(main): add cache for executeRawL2Tx 

docs/schema_design.md
fix Error: error returned from database: null value in column "id" violates not-null constraint
see also:
https://github.com/nervosnetwork/godwoken-web3/tree/main/crates/indexer/migrations
=> fix(schema): transactions.id should be BIGSERIAL

packages/api-server/src/methods/modules/gw.ts, packages/api-server/src/methods/modules/poly.ts, packages/api-server/src/methods/modules/web3.ts, packages/godwoken/src/client.ts
```sh
{
"id": "1",
"method": "poly_version",
"params": [
]
}
```
----
```sh
{
"id": "1",
"result": {
"web3Version": "0.13.0",
"web3IndexerVersion": "0.13.0",
"godwokenVersion": {
"version": "0.8.0 3342090",
"backends": [
{
"validator_code_hash": "0xc72b0ad39877b7ecd77514446588c90f6b2d4fc6b21cb9ba89b7d630fb83ce61",
"generator_code_hash": "0xc55b31d85ececa68e911424d19342faad3f636b8551074774b963fb226950dec",
"validator_script_type_hash": "0x9394306e2763a8e986b3a0f9636e628470d5d9ee8d697818e5361f74a9107b21"
},
{
"validator_code_hash": "0xdfbe6ea32e32056ac23e09bac7217729f2f4fe220c25a7429f62f66a439396f1",
"generator_code_hash": "0x10babd2de676b323d50dc7efb2fb5991568568482960a13fdc0ebfe3ef8b5025",
"validator_script_type_hash": …
```
=> feat: add poly_version rpc

packages/api-server/src/db/index.ts
- Should fix: https://github.com/nervosnetwork/godwoken-web3/issues/219
cc @RetricSu @Flouse @classicalliu
=> fix: fix getLogs 0...0

packages/api-server/package.json, packages/api-server/src/filter-web3-tx.ts, packages/godwoken/package.json, packages/godwoken/src/client.ts, packages/godwoken/src/normalizers.ts, packages/godwoken/src/rpc.ts, yarn.lock
Cherry pick from 
- https://github.com/nervosnetwork/godwoken-web3/pull/235
- https://github.com/nervosnetwork/godwoken-web3/pull/236
=> Update some deps

Cargo.lock, crates/indexer/Cargo.toml, crates/indexer/src/error_receipt_indexer.rs, crates/indexer/src/ws_client.rs, crates/rpc-client/Cargo.toml, packages/api-server/src/methods/gw-error.ts, packages/api-server/src/methods/modules/eth.ts
Related to 
- https://github.com/nervosnetwork/godwoken/pull/623
=> Cherry pick invalid exit code 92

packages/api-server/src/methods/gw-error.ts, packages/api-server/src/methods/modules/eth.ts
when a transaction in eth_estimateGas failed in godwoken, web3 will still return the gasUsed to user, while ethereum just simply throw error message. this pr fix web3 to stay same behavior with ethereum.
=> fix: don't return gasUsed when estimateGas went wrong

packages/api-server/migrations/20210308164156_init_godwoken_web3_db.ts, packages/api-server/migrations/20210805143951_accounts.ts, packages/api-server/migrations/20220126073201_rename_to_short_script_hash.ts, packages/api-server/package.json, packages/api-server/tests/db/helpers.test.ts
Prettier covers TypeScript files.
=> chore: prettier fmt typescript files

packages/api-server/src/methods/modules/eth.ts
=> chore: print toAddress when toId missing

packages/api-server/src/convert-tx.ts, packages/api-server/src/methods/modules/eth.ts, packages/api-server/src/methods/validator.ts
this pr:
- fix wrong gasLimit/gasPrice validate in `validator.ts`
- validate gasLimit range #259
=> fix: validate gasLimit params range

packages/api-server/tests/db/helpers.test.ts
deps: 
- https://github.com/nervosnetwork/godwoken-web3/pull/278
=> test: add log topic match unit test

.gitignore, README.md, packages/api-server/src/erc20.ts, packages/api-server/src/methods/modules/eth.ts
related issue(not showing erc20 balance): #284
=> chore: rm erc20 allowlist

docs/compatibility.md, packages/api-server/src/methods/constant.ts, packages/api-server/src/methods/validator.ts
close https://github.com/nervosnetwork/godwoken-web3/issues/326
----
note: we need another pr to refactor docs after we have estimated the real polyjuice gas limit according to the current cycle limit cap on godwoken.
=> chore: tune rpc gas limit cap to 50000000

packages/api-server/src/methods/modules/eth.ts
close https://github.com/nervosnetwork/godwoken-web3/issues/324
---
```sh
{
"id": 1,
"error": {
"message": "UNPREDICTABLE_GAS_LIMIT: to id missing, toAddress: 0xFb2C72d3ffe10Ef7c9960272859a23D24db9e04A. is your toAddress a valid contract account? more info: https://github.com/nervosnetwork/godwoken-web3/blob/compatibility-breaking-changes/docs/compatibility.md"
}
}
```
=> chore: improve docs when to id missing

.github/workflows/docker-publish-indexer.yml, .github/workflows/docker-publish.yml, Cargo.lock, crates/indexer/Cargo.toml, crates/indexer/migrations/20220427095638_add_exit_code_to_transactions.sql, crates/indexer/src/indexer.rs, crates/indexer/src/main.rs, crates/indexer/src/types.rs, crates/indexer/src/ws_client.rs, crates/rpc-client/Cargo.toml, docs/schema_design.md, packages/api-server/src/db/helpers.ts, packages/api-server/src/db/query.ts, packages/api-server/src/db/types.ts, packages/api-server/src/methods/gw-error.ts, packages/api-server/src/methods/modules/eth.ts, packages/godwoken/src/client.ts
Related PR:
- https://github.com/nervosnetwork/godwoken/pull/684
=> Allow to store failed transactions

packages/api-server/src/methods/constant.ts, packages/api-server/src/methods/modules/eth.ts, packages/api-server/src/methods/validator.ts
This reverts commit aaba7ed1537671aec0579d544635130c4d73b785.
=> Revert "fix: max contract code size"

package.json, packages/api-server/package.json, packages/godwoken/package.json
* Store failed transactions by @classicalliu in [#329](https://github.com/nervosnetwork/godwoken-web3/pull/329)
* Tune rpc gas limit cap to 50000000 by @RetricSu in [#330](https://github.com/nervosnetwork/godwoken-web3/pull/330)
* Allow jsonRpc params to be null by @RetricSu in [#316](https://github.com/nervosnetwork/godwoken-web3/pull/316)
* Pending transaction status should read from exit_code by @classicalliu in [#354](https://github.com/nervosnetwork/godwoken-web3/pull/354)
* Reset gw user log data max size by @classicalliu in [#338](https://github.com/nervosnetwork/godwoken-web3/pull/338)
* Remove `tx_hash_gw` by @classicalliu in [#342](https://github.com/nervosnetwork/godwoken-web3/pull/342)
* Replace missing process.env with envConfig/gwConfig by @RetricSu in …
=> chore: bump v1.1.0-rc1

crates/indexer/src/indexer.rs, packages/api-server/migrations/20220530035042_fix_transactions_contract_address.ts
- https://github.com/nervosnetwork/godwoken-web3/pull/364
=> [cherry-pick]fix: Contract should be null when not exists

packages/api-server/src/methods/validator.ts
=> fix(1.1): topic param can be null

crates/indexer/migrations/20210420113522_create_logs.sql, docs/schema_design.md
Related PR:
- https://github.com/nervosnetwork/godwoken-info/pull/33
https://github.com/nervosnetwork/godwoken-info/pull/33/files#diff-1b6a3364da7427cf0c68a0dfd827843cc4d6975611e6dc782ba6bd4704d598c1
=> fix: Check schema design

Cargo.lock, README.md, crates/indexer/Cargo.toml, crates/indexer/src/config.rs, crates/indexer/src/main.rs, crates/indexer/src/pool.rs, crates/rpc-client/src/godwoken_rpc_client.rs
web3-indexer get chain spec via `gw_get_node_info` as well.
=> feat: load node configurations using gw_get_node_info

README.md, packages/api-server/src/base/env-config.ts, packages/api-server/src/convert-tx.ts, packages/api-server/src/methods/constant.ts, packages/api-server/src/methods/modules/eth.ts, packages/api-server/src/methods/validator.ts
```sh
{
"id": 1,
"error": {
"code": -32602,
"message": "invalid argument 0: eth_sendRawTransaction parseRawTransactionData -> minimal gas price 25 required. got 1"
}
}
```
=> feat: add minimal gasPrice env

crates/indexer/src/indexer.rs
=> fix: Skip system logs if not exists (#401)

packages/api-server/src/convert-tx.ts, packages/api-server/src/methods/constant.ts, packages/api-server/src/methods/modules/eth.ts, packages/api-server/src/methods/modules/gw.ts, packages/api-server/src/methods/validator.ts
testcase: 
- https://github.com/nervosnetwork/godwoken-tests/pull/138
deps:
- https://github.com/nervosnetwork/godwoken-web3/pull/402
=> feat: validate intrinsicGas and enough fund

docs/compatibility.md
- mainnet_v1 pCKB_ERC20_Proxy contract: 0x7538C85caE4E4673253fFd2568c1F1b48A71558a (pCKB)
- testnet_v1 pCKB_ERC20_Proxy contract: 0xE05d380839f32bC12Fb690aa6FE26B00Bd982613 (pCKB)
=> docs: Update pCKB contracts

packages/api-server/src/methods/modules/eth.ts
1. when gasPrice in ethCallObj is NOT provided, we should set price to 0 instead of minGasPrice, otherwise read operation might fail the balance check.
2. when gasPrice in ethCallObj is provided, check if from address have enough balance.
```sh
{
"id": 1,
"error": {
"message": "invalid argument 0: buildEthCallTx: from account 0x2e9df163055245bfadd35e3a1f05f06096447c85 -> insufficient balance, require 56294995342131191611392, got 4213773557804335791436"
}
}
```
=> feat: validate enough fund for eth_call

packages/api-server/src/methods/modules/net.ts
=> fix: net_version should be decimal string

docs/compatibility.md
line 29: to send transaction -> to send a transaction 
line 39: do -> does
line 49: trying use -> trying to use - found on above section -> found in the above section - wrapped CKB_ERC20_Proxy in backticks
=> docs: fix syntax

packages/api-server/src/methods/modules/eth.ts
I have added some test cases, which helped me identify some bugs: https://github.com/nervosnetwork/godwoken-tests/pull/143
This PR brings some small bugfixes for them.
=> Fix some small bugs of filter methods (part 1)

packages/api-server/src/db/query.ts, packages/api-server/src/methods/modules/eth.ts
This PR improves the performance of `eth_getFilterChanges` by `BlockFilter`.
----
This PR is based on https://github.com/nervosnetwork/godwoken-web3/pull/427
=> Improves the performance of eth_getFilterChanges by BlockFilter.

README.md, packages/api-server/src/base/env-config.ts, packages/api-server/src/base/filter.ts, packages/api-server/src/block-emitter.ts, packages/api-server/src/cache/index.ts, packages/api-server/src/cache/types.ts, packages/api-server/src/db/constant.ts, packages/api-server/src/db/helpers.ts, packages/api-server/src/db/query.ts, packages/api-server/src/db/types.ts, packages/api-server/src/methods/constant.ts, packages/api-server/src/methods/modules/eth.ts, packages/api-server/tests/cache.test.ts, packages/api-server/tests/db/helpers.test.ts
I have added some test cases, which helped me identify some bugs: https://github.com/nervosnetwork/godwoken-tests/pull/143
This PR brings some small bugfixes for them, and some necessary refactoring.
----
This PR is based on https://github.com/nervosnetwork/godwoken-web3/pull/427 and https://github.com/nervosnetwork/godwoken-web3/pull/428
=> Fix and refactor eth filter methods (part 3)

README.md, packages/api-server/src/base/env-config.ts
=> chore: rm minSudtFee env

packages/api-server/src/methods/modules/gw.ts
https://github.com/nervosnetwork/godwoken/blob/develop/docs/RPC.md#method-gw_is_request_in_queue
=> feat: Add `gw_is_request_in_queue`

packages/api-server/src/convert-tx.ts, packages/api-server/src/methods/modules/eth.ts, packages/api-server/src/methods/validator.ts
- Update error message if `balance < requiredBalance` when send transaction
- Remove `balance > 0` check in `eth_call` & `eth_estimateGas`
=> fix: Update insufficient balance error message

packages/api-server/src/methods/constant.ts, packages/api-server/src/methods/modules/gw.ts, packages/api-server/src/parse-tx.ts, packages/api-server/tests/utils/fee-rate.test.ts, packages/api-server/tests/utils/parse-tx.test.ts, packages/godwoken/src/normalizers.ts, packages/godwoken/src/types.ts
deps:
- https://github.com/nervosnetwork/godwoken-web3/pull/453
=> feat: disallow meta contract tx, add parser tooling

packages/api-server/src/rate-limit.ts, packages/api-server/src/ws/methods.ts
```sh
{
"id": 1,
"error": {
"code": -32005,
"message": "Too Many Requests, IP: ::ffff:127.0.0.1, please wait 23s and retry. RPC method: web3_clientVersion."
}
}
```
=> chore: apply rate limit to ws

packages/api-server/src/methods/modules/gw.ts
Related:
- https://github.com/nervosnetwork/godwoken/pull/772
=> feat: Add rpc `gw_get_pending_tx_hashes`

packages/api-server/src/methods/gw-error.ts
before:
```sh
{
jsonrpc: '2.0',
id: 24,
error: { code: -32099, message: 'UNPREDICTABLE_GAS_LIMIT: success: ' }
}
```
---
after:
```sh
{
"id": 1,
"error": {
"message": "UNPREDICTABLE_GAS_LIMIT: out_of_gas: VM max cycle exceeded"
}
}
```
=> fix: handle error for vm max cycle exceed

crates/indexer/src/indexer.rs
Retry for about 10 times(~55s), if sill not found, return error
=> fix(indexer): Retry when tx receipt not found

packages/api-server/src/convert-tx.ts, packages/api-server/src/methods/modules/eth.ts, packages/api-server/src/methods/normalizer.ts
`eth_call` and `eth_estimateGas` required some typical process to normalize the tx params, this PR refactors such process to help better maintain the code.
=> refactor: extract call tx flow

packages/api-server/src/methods/gw-error.ts
Related to https://github.com/nervosnetwork/godwoken-web3/issues/293
This PR fixes parsing panic code from a transaction execution error, and it is enforced by a newly test case: https://github.com/nervosnetwork/godwoken-tests/pull/179/files#diff-d16ffd4c36c1b81696e960585abe75de57888131e4e95d5deedffcacb4167d36R71-R76
---
```json
{
"error" : {
"code" : -32000,
"data" : "0x4e487b710000000000000000000000000000000000000000000000000000000000000011",
"message" : "execution reverted: panic code 0x11 (Arithmetic operation underflowed or overflowed outside of an unchecked block)"
},
"id" : 0,
"jsonrpc" : "2.0"
}
```
=> fix: parse panic code from transaction error

packages/api-server/src/methods/normalizer.ts
previously we only fixed the default gas limit value in this PR https://github.com/nervosnetwork/godwoken-web3/pull/520 , in order to stay 100% the same behavior with geth, we should adjust the value if users provide ambitious gas limit as well. 
ref
- https://github.com/ethereum/go-ethereum/blob/master/internal/ethapi/api.go#L1063
=> fix(estimateGas): tune user setting gasLimit inbetween low and cap

packages/api-server/src/methods/normalizer.ts
this this pr fix such bug:
- when user balance available gas (gasCap) is lower than the intrinsicGas(gasLow), the eth_estimateGas will bypass the balance check which causes unexpected behavior.
=> fix(estimateGas): gasCap should bigger than gasLow

package.json, packages/api-server/package.json, packages/godwoken/package.json
=> chore: bump v1.7.1

package.json, packages/api-server/package.json, packages/godwoken/package.json
=> chore: bump v1.7.2

package.json, packages/api-server/package.json, packages/godwoken/package.json
=> chore: bump v1.8.4

packages/api-server/src/db/query.ts
`eth_getTransactionByNumber` should return txs order by transaction index
And `eth_getTransactionReceipt` should return logs order by log index
=> fix: Return txs in block / logs in tx in correct order

crates/indexer/src/indexer.rs, packages/api-server/migrations/20221018014620_fix_log_index.ts
Log's index should index in a block, not transaction
=> Fix log index

docs/apis.md, packages/api-server/src/filter-web3-tx.ts, packages/api-server/src/methods/modules/debug.ts, packages/api-server/src/methods/modules/gw.ts, packages/api-server/src/methods/modules/index.ts
Related:
- https://github.com/godwokenrises/godwoken/pull/846
Add two new RPC methods:
- `gw_debug_replay_transaction`
- `debug_replayTransaction`
`debug_replayTransaction` accept eth tx hash as first parameter, for example:
Request:
```json
{
"id": 1,
"method": "debug_replayTransaction",
"params": ["0xe2547056387029db3d5f5646a815290f91ed983a23171fabfcf76e74d30dd23c"]
}
```
Response:
```json
{
"id": 1,
"result": {
"return_data": "0x0000000000000000000000000000000000000000000000000000000000000001",
"logs": [
{
"address": "0x7f85301093dc5a4258d415be85c7d9e15ca8934d",
"data": "0x00000000000000000000000000000000000000000000006c6b935b8bbd400000",
"topics": [
"0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef", …
```
=> Add debug RPCs
