godwokenrises/godwoken-web3

packages/api-server/package.json, yarn.lock
provider rc10 still use v0.16.0 lumos which is not able to run on mac m1.
=> chore: bump provider 0.0.1-rc12

.dockerignore, Dockerfile, Makefile, README.md
we split the two js projects docker image into stand-alone one.
ref: 
- https://github.com/RetricSu/godwoken-polyman/commit/a06e9bea6a08ff5770c9fbb98dfbcdf6fe528de0
- https://github.com/RetricSu/godwoken-docker-js-prebuilds
=> refactor: build stand-alone docker image from Dockerfile

packages/api-server/src/db/index.ts, packages/api-server/src/methods/validator.ts
```sh
{
"method": "eth_getLogs",
"params": [
{
"fromBlock": "0x329FA",
"toBlock": "0x329FA",
"address": ["0xb66d669ea71D35e863cc2bcb7243d657c59c855f", "0x1640cf89d56d4ca90844b46851080084e8fd7745"]
}
],
"id": 1
}  
```
---
```sh
{
"id": 1,
"result": [
{
"address": "0x1640cf89d56d4ca90844b46851080084e8fd7745",
"blockHash": "0x93663e881060b39230230f58f2d790a7e08f578c0cbc3e328fbd733dbea0b0a7",
"blockNumber": "0x329fa",
"transactionIndex": "0x137",
"transactionHash": "0x1424c12954c2df97ab5ee99103f0056cc0ca3dcf751077407f5b2e4ae468762d",
"data": "0x00000000000000000000000000000000000000000000002994436442849c0000",
"logIndex": "0x0",
"topics": [
"0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef", …
```
=> fix(v0.12.x): allow address array when query logs

packages/api-server/src/methods/modules/gw.ts
```sh
{
"id": 1,
"error": {
"code": -32601,
"message": "Method not found"
}
}
```
----
```sh
{
"id": 1,
"result": {
"transaction_hash": "0x26a80599cd6093002161b126dc1176182480adc27b7ff93bf6a796fdfddf8795"
}
}
```
=> fix(main): use full node for gw_get_last_submitted_info

packages/api-server/src/cache/constant.ts, packages/api-server/src/db/index.ts, packages/api-server/src/db/types.ts, packages/api-server/src/filter-web3-tx.ts, packages/api-server/src/methods/modules/eth.ts, packages/api-server/src/ws/methods.ts
[BREAK_CHANGES]: 
the following api methods will use eth-tx-hash instead of gw-tx-hash both in input params and output return value.
- eth_getBlockByHash
- eth_getBlockByNumber
- eth_getTransactionByHash
- eth_getTransactionByBlockHashAndIndex
- eth_getTransactionByBlockNumberAndIndex
- eth_getTransactionReceipt
- eth_getFilterChanges
- eth_getLogs
- eth_sendRawTransaction
in-order to covert eth-tx-hash to gw-tx-hash for instant-finality transaction(which is not in database yet) , we save redis tx-hash-mapping in redis. the expired time is set to 30 minutes. for error-tx-receipt, since the error tx will be deleted from database(after 3 blocks), 30 minutes should be longer than 3 blocks.
=> BREAKING CHANGE: use eth-tx-hash for eth_* api methods

Cargo.lock, crates/indexer/Cargo.toml, crates/indexer/src/error_receipt_indexer.rs, crates/indexer/src/ws_client.rs, crates/rpc-client/Cargo.toml, packages/api-server/src/methods/gw-error.ts, packages/api-server/src/methods/modules/eth.ts
RPC returns by execute tx:
```json
{
"code": -32600,
"message": "sudt_error_insufficient_balance: sender doesn't have enough funds to send tx",
"data": {
"failed_reason": {
"status_code": "0x5c",
"status_type": "SUDT_ERROR_INSUFFICIENT_BALANCE",
"message": "sender doesn't have enough funds to send tx"
}
}
}
```
And example error receipt:
```json
{
"id": 2,
"result": {
"transactionHash": "0x143cf50c044ef1bf258f972d4fd4315f1592b4b4fab1c92a1035936e81a75659",
"blockHash": "0x25b7727209048f7ed890adee777a3938759350c62db0ad729f824930a5ceb21d",
"blockNumber": "0x537",
"transactionIndex": "0x0",
"gasUsed": "0x4e8c",
"cumulativeGasUsed": "0x4e8c",
"logsBloom": "0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 …
```
=> fix: Error info for invalid exit code 92

README.md, crates/indexer/src/config.rs, crates/indexer/src/indexer.rs, crates/indexer/src/runner.rs, packages/api-server/src/base/env-config.ts, packages/api-server/src/methods/modules/poly.ts, scripts/generate-indexer-config.js
- https://github.com/nervosnetwork/godwoken-web3/issues/198
in this pr:
- remove the `chain_Id` env
- add `compatible_chain_id` instead
- and calculating chain_id with creator_id and compatible_chain_id
=> fix(indexer): support compatible_chain_id for calculating eth_tx_hash

.github/workflows/docker-publish-indexer.yml, .github/workflows/docker-publish.yml
- new-commit-build: for `ghcr.io` aka github packages, make ci build image every time we push new commit to branch.
- official-release-build: for docker image, make ci build image only when we release new tag.
requirement:
- `secrets.GHP_CRT`
=> chore: allow ci to build for new commit in ghcr

packages/api-server/src/base/address.ts, packages/api-server/src/convert-tx.ts, packages/api-server/src/filter-web3-tx.ts, packages/api-server/src/methods/constant.ts, packages/api-server/src/methods/modules/eth.ts, packages/api-server/src/methods/validator.ts
---
after this pr, when you call eth_estimateGas for contract deployment (no to_address), the rpc will work as exepectd:
```sh
{
"id": 1,
"method": "eth_estimateGas",
"params": [
{
"from": "0xFb2C72d3ffe10Ef7c9960272859a23D24db9e04A",
"value": "0x1",
"data": "0x6080604052607b60008190555060c68061001a6000396000f3fe60806040526004361060265760003560e01c806360fe47b114602b5780636d4ce63c146056575b600080fd5b605460048036036020811015603f57600080fd5b8101908080359060200190929190505050607e565b005b348015606157600080fd5b5060686088565b6040518082815260200191505060405180910390f35b8060008190555050565b6000805490509056fea265627a7a7231582001528e3c7dc7db53b0434c7bd349b2eb25952284d11bddc8f51bfac5522eabf764736f6c63430005100032"
},
"latest"
]
}
```
```sh
{
"id": 1,
"result": …
```
=> fix: distinct zero address and deploy to address

docs/compatibility.md, packages/api-server/src/convert-tx.ts, packages/api-server/src/methods/constant.ts, packages/api-server/src/methods/gw-error.ts
=> fix: return clear error when transfering eoa to eoa in related RPCs

README.md, packages/api-server/src/base/env-config.ts, packages/api-server/src/methods/modules/eth.ts, packages/api-server/src/methods/modules/poly.ts
releated issue:
- https://github.com/nervosnetwork/godwoken-web3/issues/210
=> fix(eth_call): use default from_id instead of default_from_address

packages/api-server/src/base/address.ts, packages/api-server/src/cache/store.ts
- noticed that since the ethAddressToScriptHash mapping is not changeable, we set the cache in redis to have no expired time.
=> feat: add cache for ethAddressToScriptHash

packages/api-server/package.json, packages/api-server/src/convert-tx.ts, packages/api-server/src/filter-web3-tx.ts, packages/godwoken/package.json, packages/godwoken/src/client.ts, packages/godwoken/src/normalizers.ts, packages/godwoken/src/rpc.ts, yarn.lock
For `cross-fetch` and `jsbi` as `@ckb-lumos/toolkit`'s peer dep, we should add those to deps manually.
=> Update lumos version

packages/api-server/src/methods/validator.ts
Error constructor function should return error but not throw error.
=> fix: throw error in constructor

docs/compatibility.md
The `to` member of a Godwoken transaction must be a contract.
=> docs: `transaction.to` MUST be a Contract Address

packages/api-server/src/convert-tx.ts, packages/api-server/src/methods/error.ts, packages/api-server/src/methods/modules/eth.ts, packages/api-server/src/methods/validator.ts
this pr refactor `validator.ts` file to:
- enable more clear structure / reduce some repeated code
- impl correct return type in function instead of any type
- pass context to give user a more clear params error message
---
```sh
{
"id": 73,
"error": {
"code": -32602,
"message": "invalid argument 0: invalid argument"
}
}                        
```
to
```sh
{
"id": 2,
"error": {
"code": -32602,
"message": "invalid argument 0: filter topic[] Array -> expect topic string has 32 bytes, but getting 4 bytes"
}
}
```
close #247
=> refactor(validator): verify params with correct types and full context

packages/api-server/src/methods/validator.ts
Metamask transaction params allow for leading zero in HexNumber
=> fix: allow leading zero in HexNumber params

packages/api-server/src/methods/gw-error.ts
Update revert messages
For `assert(false)`, it will cause `Panic(0x1)`, returns error message: 
```
revert: reverted with panic code 0x1 (Assertion error)
```
For `require("ReentrancyAttack: failed call")` it will case `Error(string)` returns error message
```
revert: Error(ReentrancyAttack: failed call)
```
More info for `Panic(uint256)` and `Error(string)` build-in error: [solidity doc](https://docs.soliditylang.org/en/v0.8.13/control-structures.html#panic-via-assert-and-error-via-require)
For custom error like 
```solidity
error Empty();
function testEmpty() public view returns(bool){
revert Empty();
return true;
}
```
It will return
```
revert: reverted with custom error
```
=> Build in return data

packages/api-server/src/middlewares/jayson.ts
close #313 
```sh
{
"id": 1,
"method": "eth_blockNumber",
"params": null
}
```
result
```sh
{
"id": 1,
"result": "0x1b4b"
}
```
=> fix: allow jsonRpc params to be null

README.md, packages/api-server/src/app/app.ts, packages/api-server/src/app/www.ts, packages/api-server/src/base/env-config.ts, packages/api-server/src/methods/index.ts, packages/api-server/src/methods/modules/eth.ts, packages/api-server/src/ws/wss.ts, packages/godwoken/src/rpc.ts
we have some missing config still using `process.env.` instead of `envConfig` or `gwConfig`. this pr refactor such code.
=> refactor: replace missing process.env with envConfig/gwConfig

.github/workflows/godwoken-tests.yml, .github/workflows/unit-tests.yml, package.json, packages/api-server/tests/cache.test.ts, packages/api-server/tests/methods/eth.test.ts, packages/api-server/tests/methods/net.test.ts, packages/api-server/tests/www.ts
This PR creates 2 workflows:
- unit-tests.yml, run godwoken-web3's unit tests
- godwoken-tests.yml, run godwoken-tests's tests
Note that I remove two broken test cases temporarily:
- [test.serial "install with address less than 20 bytes-length"](https://github.com/nervosnetwork/godwoken-web3/blob/unit-test-workflow/packages/api-server/tests/cache.test.ts#L15-L33)
- [test "net_listening"](https://github.com/nervosnetwork/godwoken-web3/blob/unit-test-workflow/packages/api-server/tests/methods/net.test.ts#L15-L20)
=> test: create workflows unit-tests.yml and godwoken-tests.yml

crates/indexer/src/indexer.rs, packages/api-server/migrations/20220530035042_fix_transactions_contract_address.ts
Transaction's `contract_address` should be null when not exist.
=> fix: Contract should be null when not exists

.github/workflows/godwoken-tests.yml
With this update, we can create PR from fork repos now.
The target godwoken-tests workflow: https://github.com/nervosnetwork/godwoken-tests/blob/simplify-workflow/.github/workflows/reusable-integration-test-v1.yml
Test run example: https://github.com/keroro520/godwoken-web3/runs/6651154508?check_suite_focus=true
=> feat: reuse simplified godwoken-test workflow

packages/api-server/src/methods/validator.ts
```sh
{
"method": "eth_newFilter",
"params": [
{
"topics": [null, "0xFb2C72d3ffe10Ef7c9960272859a23D24db9e04A272859a23D24db9e04A27285", null]
}
],
"id": 1
}
```
---
before
```sh
{
"id": 1,
"error": {
"code": -32602,
"message": "invalid argument 0: filter topic[] Array -> topic string -> hexString argument must be a string type"
}
}
```
after
```sh
{
"id": 1,
"result": "0x7f70ca2221f1bf40195e28b1b8e4ab25"
}
```
=> fix: topic param can be null

crates/indexer/src/indexer.rs
For example: `Error: no system logs in tx_hash: 0x7a3de1cf7537520145b97292c0670dd8ba1118cd7be4e00f429a59959653e13d, block_number: 377, index: 4`
=> chore: Update no system logs message

packages/api-server/src/methods/gw-error.ts
`eth_call` RPC:
Godwoken Web3:
Update revert message format, for hardhat revert message need `data.message` and `data.data`，and `data.message` should in specific format.
For example: `Error: call revert exception; VM Exception while processing transaction: reverted with reason string "12341123411234112341123411234112341123411234112341123411234112341123411234112341123411234112341123411234112341123411234112341123411234112341123411234112341123411234112341"`
```json
{
"id": 2,
"error": {
"message": "revert: Error: VM Exception while processing transaction: reverted with reason string '12341123411234112341123411234112341123411234112341123411234112341123411234112341123411234112341123411234112341123411234112341123411234112341123411234112341123411234112341'", …
```
=> fix: Update revert error message and data

packages/api-server/src/db/query.ts
According to [the database schema](https://github.com/nervosnetwork/godwoken-web3/blob/7e689c50a7a8680717e0f8228f4c54f73da4038b/docs/schema_design.md#L23), `transaction.block_hash` is `bytea` but not text.
=> fix: correct parameter type of SQL query of eth_getBlockTransactionCountByHash

packages/api-server/src/convert-tx.ts, packages/api-server/src/methods/modules/eth.ts, packages/godwoken/src/client.ts, packages/godwoken/src/types.ts
Check auto create tx exists when call RPC `eth_getTransactionByHash`
=> feat: Delete dropped auto create account tx

crates/indexer/src/types.rs
Fix for eth_tx_hash calculation in indexer, the `eth_tx_hash` will be wrong when r / s with leading zeros
Note: 
Need to resync database to fix old data.
=> fix(indexer): r & s in rlp encode should be integer rather than bytes

docker/indexer/Dockerfile
this ci is always failed... https://github.com/nervosnetwork/godwoken-web3/runs/7532460024?check_suite_focus=true
seems Ubuntu 21.04 (along with all flavors) is End-of-Life and thus unsupported on many sites? https://askubuntu.com/questions/1420130/cannot-do-apt-update-ip-address-not-found-no-release-file
Not sure if ubuntu 22.04 will change the behavior of web3-indexer via build
=> fix(ci): upgrade baseimage to 22.04

packages/api-server/src/methods/modules/eth.ts, packages/api-server/src/methods/types.ts, packages/api-server/src/methods/validator.ts, packages/api-server/src/util.ts
```sh
{
"method": "eth_call",
"params": [
{
"from": "0x966b30e576a4d6731996748b48dd67c94ef29067",
"to": "0x45b2585ee6877b36e359603eae3c465392b57d13",
"data": "0xb67d77c500000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000006"
},
{
"blockHash": "0x65b3f50d57e73112852d926f5f18cd5714a487c81ed9da1b9a1a9bd16a9e2d81",
"requireCanonical": false
}
],
"id": 1
}
```
---
```sh
{
"id": 1,
"result": "0x0000000000000000000000000000000000000000000000000000000000000002"
}
```
- https://eips.ethereum.org/EIPS/eip-1898
- https://github.com/ethereum/go-ethereum/pull/19491
- https://github.com/nervosnetwork/godwoken-tests/pull/166
=> feat: add blockSpecifer for blockParameter to support Eip1898

crates/indexer/src/indexer.rs, crates/indexer/src/runner.rs, crates/indexer/src/types.rs, docs/compatibility.md, packages/api-server/cli/fix-eth-tx-hash.ts, packages/api-server/src/convert-tx.ts
Related:
- https://github.com/nervosnetwork/godwoken/pull/777
=> feat: Support non eip155 tx

docs/apis.md, docs/poly-apis.md, packages/api-server/src/db/query.ts, packages/api-server/src/methods/constant.ts, packages/api-server/src/methods/modules/poly.ts, packages/godwoken/src/client.ts, scripts/health-check.sh
```sh
{
"id": 2,
"method": "poly_getHealthStatus",
"params": []
}
```
---
```sh
{
"id": 2,
"result": {
"status": true,
"pingNode": "pong",
"pingFullNode": "pong",
"pingRedis": "PONG",
"isDBConnected": true,
"syncBlocksDiff": 0
}
}
```
=> feat: add poly_getHealthStatus api and health-check script

packages/api-server/src/methods/modules/eth.ts, packages/api-server/src/methods/validator.ts
Fix https://github.com/nervosnetwork/godwoken-web3/issues/507
Cause: [EIP-1474 declares the storage position as `Quantity` type](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1474.md#eth_getstorageat) but we declare it as `HexString`.
=> fix: declare StorageKey as HexNumber type

packages/api-server/src/cache/data.ts, packages/api-server/src/methods/error-code.ts, packages/api-server/src/methods/error.ts, packages/api-server/src/methods/gw-error.ts, packages/api-server/src/methods/modules/eth.ts, packages/api-server/src/methods/modules/gw.ts, packages/api-server/tests/methods/gw.test.ts, packages/godwoken/src/types.ts
Main contribution:
- Fix https://github.com/nervosnetwork/godwoken-web3/issues/423
- Refactor handling of godwoken error.
Because the `gw-error` module has been almost rewritten, I suggest reviewers read the file directly: https://github.com/nervosnetwork/godwoken-web3/blob/fc9ba1bced40ac38ecc2f5b4a7bd033952540a45/packages/api-server/src/methods/gw-error.ts
- Remove `error.data.failed_reason` and `error.data.message` from error JSONRPC response.
See also: https://github.com/nervosnetwork/godwoken-web3/discussions/511
---
Others:
- Add test cases: https://github.com/nervosnetwork/godwoken-tests/pull/179/
- Remove handling of [`Err("can't find backend for script_hash")`](https://github.com/nervosnetwork/godwoken-web3/blob/98e4dc1e44a6b4530910b428bf66898516752ae7/packages/api-server/src/metho …
=> refactor: handling godwoken error

packages/api-server/newrelic.js, packages/api-server/src/methods/index.ts, packages/api-server/src/methods/validator.ts
Our error responses are not automatically collected by NewRelic because we use Jayson instead of express' error handler.
This PR use `newrelic.noticeError` to collect errors into NewRelic.
=> feat: use newrelic to collect errors

packages/api-server/src/convert-tx.ts
this bug was introduced by this [commit](https://github.com/godwokenrises/godwoken-web3/commit/2c076adebeb87c01b3e53676bda6437360eba3f3#diff-cce75f92de0f01f77430b0195c78d8a547ca11f2b8f818202008dce92a69ebefR1378) which will cause calling raw tx to transfer native token with non-empty `tx.data` filed to the wrong address and create a new account in polyjuice. Since it is call only, it will not have actual effect on-chain.
=> fix(call): poly args data byte length

packages/api-server/src/block-emitter.ts, packages/api-server/src/cache/constant.ts, packages/api-server/src/db/knex.ts, packages/api-server/src/db/query.ts
- machine: apple m1 8c 16g
- start web3: `yarn build && PG_POOL_MAX=10 LOG_LEVEL=error yarn start:prod`
- autocannon rpc bench: https://github.com/RetricSu/rpc-bench `yarn && yarn start`
main [7da1981](https://github.com/nervosnetwork/godwoken-web3/commit/7da198190f271cd174864ee031a2907c1d08b2be)
```sh
eth_blockNumber => TPS: 3617.59 (+361659.00%), Latency: 275.56ms (+27456.00%)
eth_getBlockByNumber => TPS: 1364.34 (+136334.00%), Latency: 725.93ms (+72493.00%)
eth_getTransactionReceipt => TPS: 1015.55 (+101455.00%), Latency: 970.59ms (+96959.00%)
eth_getLogs => TPS: 1039.96 (+103896.00%), Latency: 948.93ms (+94793.00%)
```
cache branch:
```sh
eth_blockNumber => TPS: 8354.35 (+130.94%), Latency: 120.10ms (-56.42%)
eth_getBlockByNumber => TPS: 5392.64 (+295.26%), Latency: 185.56ms (-74.44%) …
```
=> feat: simple db cache plugin

.github/workflows/godwoken-tests.yml, .github/workflows/unit-tests.yml, README.md, crates/indexer/Cargo.toml, crates/indexer/src/indexer.rs, crates/indexer/src/insert_l2_block.rs, crates/indexer/src/main.rs, crates/indexer/src/pool.rs, crates/indexer/src/runner.rs, crates/rpc-client/Cargo.toml, packages/api-server/migrations/20221102080006_add_chain_id_to_transactions.ts, packages/api-server/src/convert-tx.ts, packages/api-server/src/db/helpers.ts, packages/api-server/src/db/types.ts, packages/api-server/src/filter-web3-tx.ts
Related:
- fix https://github.com/godwokenrises/godwoken-web3/issues/566
`v` in `eth_getTransactionByHash` returns `signature_v`(equals to "0x0" or "0x1") before.
Now, it returns
- `v = chain_id * 2 + 35 + signature_v` for EIP155 tx
- `v = 27 + signature_v` for others
NOTE:
Need to resync or run update command by `./gw-web3-indexer update`
=> Fix eip155 v

.github/workflows/godwoken-tests.yml, README.md, docs/addtional-feature.md, packages/api-server/src/methods/index.ts, packages/api-server/src/methods/modules/eth.ts, packages/api-server/src/middlewares/jayson.ts, packages/api-server/src/util.ts, packages/api-server/src/ws/methods.ts
RPC method updated in this PR:
- `eth_getTransactionReceipt`
- RPC which support block parameter, except for
- `eth_getBlockByNumber`
- `eth_getBlockTransactionCountByNumber`
- `eth_getTransactionByBlockNumberAndIndex`
which does not support pending in our code since a long time ago, we might need to check those 3 RPC methods later
In this pr, we use different RPC URLs to tell if the instant-finality-hack mode is enabled so that we can provide the feature for user while keeping other users who care more about compatibility than such feature happy as well.
Notice how the integration tests last longer in non-instant-finality mode, this can be reduced after we finished the following todos: 
---
TODO before PR merge:
- https://github.com/godwokenrises/godwoken-tests/pull/201
One test case is …
=> refactor: instant-finality feature via special RPC url

packages/api-server/src/methods/modules/eth.ts
Related:
- https://github.com/godwokenrises/godwoken-web3/issues/569
Return `0x` when `eth_getCode`'s first parameter equals zero address
=> fix: Return 0x when eth_getCode with zero address

packages/api-server/src/db/query.ts
This PR rm tip block db query cache to reduce the integration test time from 15m to 4m - https://github.com/godwokenrises/godwoken-web3/actions/runs/3515284891/jobs/5890349513
---
ideally, we should observe the requests to decide whether to use cache for specific db query selections or not. This can be done later in our online environment.
=> chore: rm tip block cache to improve ci speed

packages/api-server/src/app/cluster.ts
opentelemetry should start before logger initialization.
=> fix: no trace info in winston log

packages/api-server/src/filter-web3-tx.ts, packages/api-server/src/methods/error.ts, packages/api-server/src/methods/exit-code.ts, packages/api-server/src/methods/gw-error.ts, packages/api-server/src/methods/index.ts, packages/godwoken/src/types.ts
some examples:
contract revert 
```sh
{
"id": 1,
"error": {
"code": -32000,
"message": "execution reverted: here is a simple revert reason",
"data": "0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000001e6865726520697320612073696d706c652072657665727420726561736f6e0000",
"extra": {
"exit_code": "0x2",
"message": "revert",
"stack": "EVMC"
}
}
}
```
max cycles
```sh
{
"id": 1,
"error": {
"code": -32000,
"message": "out of gas(vm reached max cycles)",
"extra": {
"exit_code": "0xff",
"message": "vm reached max cycles",
"stack": "GODWOKEN"
}
}
}
```
solidity call baseFee opcode
```sh
{
"id": 1,
"error": {
"code": -32000,
"message": "undefined instruction", …
```
=> feat: add error code mapping for gw/polyjuice/evmc
